spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bdnode5:3306/onework?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1qaz@WSX
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariPool
      max-lifetime: 120000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            useProperties: false
            tablePrefix: QRTZ_
            misfireThreshold: 60000
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

onework:
  flink:
    checkpoint: hdfs:///user/flink/checkpoint
    savepoint: hdfs:///user/flink/savepoint
  yarn:
    site-file: /home/kangjiao/hadoop_conf/yarn-site-dd.xml
    queue: root.streaming
    session-appname: onework
  hdfs:
    file-owner: hdfs
    core-site-file: /home/kangjiao/hadoop_conf/core-site-dd.xml
    hdfs-site-file: /home/kangjiao/hadoop_conf/hdfs-site-dd.xml

logging:
  level:
    root: info